name: Execute Vertex AI Pipelines Job

on:
  push:
    branches:
      - main


env:
  GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GCP_REGION: ${{ secrets.GCP_REGION }}
  GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
  GCP_STORAGE_BUCKET: ${{ secrets.GCP_STORAGE_BUCKET }}
  DEPLOY_PIPELINE_ROOT: ${{ secrets.DEPLOY_PIPELINE_ROOT }}
  SERVING_IMAGE_URI: ${{ secrets.SERVING_IMAGE_URI }}
  MODEL_ARTIFACT_URI: ${{ secrets.MODEL_ARTIFACT_URI }}
  ENDPOINT_ARTIFACT_URI: ${{ secret.ENDPOINT_ARTIFACT_URI}}
  DEPLOY_MACHINE_TYPE: ${{ vars.DEPLOY_MACHINE_TYPE }}
  DEPLOY_ACCELERATOR_TYPE: ${{ vars.DEPLOY_ACCELERATOR_TYPE }}
  AUTOSCALING_NODES_MIN: ${{ vars.AUTOSCALING_NODES_MIN }}
  AUTOSCALING_NODES_MAX: ${{ vars.AUTOSCALING_NODES_MAX }}
  AUTOSCALING_TARGET_CPU: ${{ vars.AUTOSCALING_TARGET_CPU }}
  TRAFFIC_PERCENTAGE: ${{ vars.TRAFFIC_PERCENTAGE }}


jobs:
  execute_pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Configure Google Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          version: '354.0.0'
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}

      - name: Configure Docker
        uses: docker/setup-buildx-action@v1
      
      - name: Execute deployment script
        run: |
          chmod +x ./automation_scripts/deploy/execute.sh
          ./automation_scripts/deploy/execute.sh
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: username/image-name:latest
      
      - name: Execute Vertex AI Pipelines Job
        uses: google-github-actions/vertex-ai-pipelines@main
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          location: ${{ secrets.GCP_REGION }}
          api_key: ${{ secrets.API_KEY }}
          job_spec_path: path/to/job_spec.yaml
          container_image_uri: gcr.io/my-project/my-container:latest